name: Unit Tests # name of the test

on:
 push:
   branches: [main]  # or 'master' if that's your primary branch name
 pull_request:
   branches: [main] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
 tests: # the name of your status check, will become important when you do branch protection
   runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
   steps:
     - uses: actions/checkout@v4 # using version 4 of Actions

     # Set up and test server
     - name: Set up Node for server
       uses: actions/setup-node@v4
       with:
         node-version: '16'

     - name: Install server dependencies
       working-directory: ./server
       run: npm install

    # - name: Run server tests
    #   working-directory: ./server
    #   run: npm test

     # Set up and test client
     - name: Set up Node for client
       uses: actions/setup-node@v4
       with:
         node-version: '16'
         
     - name: Install client dependencies
       working-directory: ./client
       run: npm install
       
     - name: Run client tests
       working-directory: ./client
       run: npm test
